version: '3.8'
services:
  mongodb:
    image: mongo:6.0
    container_name: campusmarket-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7.2
    container_name: campusmarket-redis
    ports:
      - '6379:6379'

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: campusmarket-zookeeper
    ports:
      - '2181:2181'

  kafka:
    image: wurstmeister/kafka:2.13-2.8.0
    container_name: campusmarket-kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  auth-service:
    build:
      context: ./auth-service
    container_name: campusmarket-auth
    ports:
      - '3001:3001'
    depends_on:
      - mongodb
      - kafka
      - redis
    environment:
      - NODE_ENV=development

  user-service:
    build:
      context: ./user-service
    container_name: campusmarket-user
    ports:
      - '3002:3002'
    depends_on:
      - mongodb
      - kafka
      - redis
    environment:
      - NODE_ENV=development

  marketplace-service:
    build:
      context: ./marketplace-service
    container_name: campusmarket-marketplace
    ports:
      - '3003:3003'
    depends_on:
      - mongodb
      - kafka
      - redis
    environment:
      - NODE_ENV=development

  api-gateway:
    build:
      context: ./api-gateway
    container_name: campusmarket-gateway
    ports:
      - '3000:3000'
    depends_on:
      - auth-service
      - user-service
      - marketplace-service
    environment:
      - NODE_ENV=development

volumes:
  mongo_data:
